#C:\Users\LAB-A-21-10\ansible\final\apache2.conf
Listen 8080
ServerName localhost

# Minimal working Apache2 config
ServerRoot "/etc/apache2"
ServerName localhost

# PidFile
PidFile ${APACHE_PID_FILE}

# Timeout
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

# Logging
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn
CustomLog ${APACHE_LOG_DIR}/access.log combined

# Default document root
DocumentRoot /var/www/html

<Directory />
    Options FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

# Include additional configs
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf
